name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test:
    strategy:
      matrix:
        java-version: [ 11, 17 ]
        java-distribution: [ 'temurin' ]
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

 
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'

      - name: Setup coursier cache
        uses: coursier/cache-action@v6.4

      - name: Test
        run: ./sbt featherweightGoCoreJVM/test

      - name: Run `Main.main`
        run: ./sbt featherweightGoJVM/run

      - name: Check to compile JS code
        run: ./sbt featherweightGoJS/fastOptJS


