name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup coursier cache
        uses: coursier/cache-action@v6.4

      - name: Make JS code
        run: ./sbt featherweightGoJS/fastOptJS

      - name: Prepare to publish
        run: |
          mkdir -p ./public/js/target/scala-2.13
          cp index.html ./public/
          cp ./js/target/scala-2.13/featherweightgo-fastopt.js ./public/js/target/scala-2.13/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
